### ISSUE TITLE
grpc/grpc-web build fails

### ISSUE THREAD

**Issue by johanbrandhorst** [johanbrandhorst/grpc-web-compatibility-test#1]
The build fails with the following error in my testing:

```
/go/src/github.com/johanbrandhorst/grpc-web-compatibility-test/frontend/grpcwebtext $ ./node_modules/.bin/webpack
Hash: 6d4e8d996f18d6c72d53
Version: webpack 4.28.3
Time: 2209ms
Built at: 04/01/2019 20:17:29
    Asset      Size  Chunks             Chunk Names
bundle.js  1.21 MiB    main  [emitted]  main
Entrypoint main = bundle.js
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
[./proto/EchoServiceClientPb.ts] 741 bytes {main} [built] [failed] [3 errors]
[./proto/echo_pb.js] 35.6 KiB {main} [built]
[./src/index.ts] 3.41 KiB {main} [built]
    + 7 hidden modules

ERROR in ./proto/EchoServiceClientPb.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /go/src/github.com/johanbrandhorst/grpc-web-compatibility-test/frontend/grpcwebtext/proto/EchoServiceClientPb.ts.
    at makeSourceMapAndFinish (/go/src/github.com/johanbrandhorst/grpc-web-compatibility-test/frontend/grpcwebtext/node_modules/ts-loader/dist/index.js:78:15)
    at successLoader (/go/src/github.com/johanbrandhorst/grpc-web-compatibility-test/frontend/grpcwebtext/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (/go/src/github.com/johanbrandhorst/grpc-web-compatibility-test/frontend/grpcwebtext/node_modules/ts-loader/dist/index.js:22:12)
 @ ./src/index.ts 4:28-67

ERROR in /go/src/github.com/johanbrandhorst/grpc-web-compatibility-test/frontend/grpcwebtext/proto/EchoServiceClientPb.ts
./proto/EchoServiceClientPb.ts
[tsl] ERROR in /go/src/github.com/johanbrandhorst/grpc-web-compatibility-test/frontend/grpcwebtext/proto/EchoServiceClientPb.ts(119,7)
      TS2345: Argument of type 'ServerStreamingEchoRequest' is not assignable to parameter of type 'Request'.
  Type 'ServerStreamingEchoRequest' is missing the following properties from type 'Request': cache, credentials, destination, headers, and 19 more.

ERROR in /go/src/github.com/johanbrandhorst/grpc-web-compatibility-test/frontend/grpcwebtext/proto/EchoServiceClientPb.ts
./proto/EchoServiceClientPb.ts
[tsl] ERROR in /go/src/github.com/johanbrandhorst/grpc-web-compatibility-test/frontend/grpcwebtext/proto/EchoServiceClientPb.ts(138,7)
      TS2345: Argument of type 'ServerStreamingEchoRequest' is not assignable to parameter of type 'Request'.
```

This is because of https://github.com/grpc/grpc-web/issues/416, I submitted a fix in https://github.com/grpc/grpc-web/pull/429.

Manually fixing this exposes the second bug https://github.com/grpc/grpc-web/issues/428, which I submitted another fix for in https://github.com/grpc/grpc-web/pull/430.

Once both of these are merged and the generator has been released we can close this issue.

**Comment by johanbrandhorst** [comment]
According to https://github.com/grpc/grpc-web/issues/463, a new release is imminent.

**Comment by johanbrandhorst** [comment]
Ah, this has since been fixed.
